name: Go

on: push

env:
  # rewrite go env GOCACHE to something well known so we can use actions/cache with it
  GOCACHE: "/home/runner/go/cache"
  CLI: "v0.38.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/go/src
          /hone/runner/go/cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Print Go Version
      run: go version

    - name: Build
      run: go build -mod=readonly -v .

  test:
    name: "Test"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install forge CLI
      run: |
        wget https://github.com/stormforger/cli/releases/download/${CLI}/forge_${CLI}_linux_amd64.tar.gz
        tar -xzf forge_${CLI}_linux_amd64.tar.gz
        ./forge version

    - name: Run Validation Run
      run: |
        ./forge test-case launch "demo/example-github-actions" --validate --test-case-file="./hello-world.js" \
          --title="Job=${{github.run_number}} Branch=${{github.ref}}" --notes="Name | Value
          --- | ---
          Ref | ${{github.ref}}
          Sha | ${{github.sha}}
          Run#   | ${{github.run_number}}
          RunID  | ${{github.run_id}}
          Sender | ${{github.event.sender.login}}
          "
      env:
        STORMFORGER_JWT: ${{ secrets.STORMFORGER_JWT }}

  deploy:
    name: "Deploy (Production)"
    needs: [test]
    runs-on: ubuntu-latest
    # run the deploy pipeline on master only
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install forge CLI
      run: |
        wget https://github.com/stormforger/cli/releases/download/${CLI}/forge_${CLI}_linux_amd64.tar.gz
        tar -xzf forge_${CLI}_linux_amd64.tar.gz
        ./forge version

    - name: Run Load-Test
      run: |
        ./forge test-case launch "demo/example-github-actions" --test-case-file="./hello-world.js" --watch \
        --title="Job=${{github.run_number}} Branch=${{github.ref}}" --notes="Name | Value
        --- | ---
        Ref | ${{github.ref}}
        Sha | ${{github.sha}}
        Run#   | ${{github.run_number}}
        RunID  | ${{github.run_id}}
        Sender | ${{github.event.sender.login}}
        "
      env:
        STORMFORGER_JWT: ${{ secrets.STORMFORGER_JWT }}
